# Generated by Django 2.0.2 on 2018-02-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
