# Generated by Django 2.0.2 on 2018-02-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserInfo'),
        ),
    ]
